let Favorite_Fruit= ["Banana","Apple","Mango"]
console.log(Favorite_Fruit.includes("Banana"))
console.log(Favorite_Fruit.includes("Apple"))
console.log(Favorite_Fruit.includes("Mango"))
if (Favorite_Fruit.includes("Apple")) 
    console.log("You Like Apples")
    if (Favorite_Fruit.includes("Banana")) 
    console.log("You Like Banana")
    if (Favorite_Fruit.includes("Banana")) 
    console.log("You Like Banana")